# Generated by Django 6.0.3 on 2026-03-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_checkout_quantity_alter_checkout_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
