# Generated by Django 6.0.3 on 2026-03-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='zip_code',
            field=models.IntegerField(),
        ),
    ]
