# Generated by Django 6.0.3 on 2026-03-09 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_checkout_quantity_alter_checkout_user'),
        ('user', '0002_alter_userdata_phone_alter_userdata_zip_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('zip_code', models.IntegerField()),
                ('province', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('total_payment', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='userhistory',
            old_name='total_payment',
            new_name='total_amount',
        ),
        migrations.AddField(
            model_name='userhistory',
            name='user_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.userorder'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
