# Generated by Django 6.0.3 on 2026-03-10 18:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userorder_alter_userhistory_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhistory',
            name='date',
        ),
        migrations.AddField(
            model_name='userorder',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
