# Generated by Django 6.0.3 on 2026-03-10 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_userhistory_date_userorder_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorder',
            name='total_payment',
        ),
    ]
