# Generated by Django 6.0.3 on 2026-03-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_userhistory_user_userorder_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhistory',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='userorder',
            name='total_amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
