# Generated by Django 6.0.3 on 2026-03-12 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_userhistory_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhistory',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
